%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Nathan\Downloads\test.csv
%
% Auto-generated by MATLAB on 09-Apr-2025 20:11:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9, "Encoding", "UTF-8");

%delimiters
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% column names and types
opts.VariableNames = ["time", "ThiMean", "ThiStd", "ThoMean", "ThoStd", "TciMean", "TciStd", "TcoMean", "TcoStd"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import
tbl = readtable("C:\Users\nqoke\Downloads\416TEST1.csv", opts);
% 
%% Convert to output type
time = tbl.time;
ThiMean = tbl.ThiMean;
ThiStd = tbl.ThiStd;
ThoMean = tbl.ThoMean;
ThoStd = tbl.ThoStd;
TciMean = tbl.TciMean;
TciStd = tbl.TciStd;
TcoMean = tbl.TcoMean;
TcoStd = tbl.TcoStd;

%% Clear temporary variables
clear opts tbl

%LMTD Calc
LMTDMatrix=((ThiMean-TciMean)-(ThoMean-TcoMean))./(log((ThiMean-TciMean)/(ThoMean-TcoMean)));
LMTD=LMTDMatrix(:,1);


hotDelta=(ThiMean-ThoMean);


%hot side has Cmin
%effectiveness
epsilonMatrix=(ThiMean-ThoMean)./(ThiMean-TciMean);
epsilon=epsilonMatrix(:,1);

%effeciency
etaMatrix=(ThiMean-ThoMean)./(TciMean-ThiMean);
eta=etaMatrix(:,1);

%U Calc
kSteel=15; %W/mK
mDot=0.08412026; %(kg/s)
h=500; %W/m^2K
Rout=0.0508; %m
Rin=0.04445; %m
L=0.4572; %m

Rwall=(log(Rout/Rin))/(2*pi*kSteel*L);
A=0.00381*2*pi*L;
U=1/((1/h)+(1/h)+(Rwall/A));

[maxETA, idx1] =max(eta);
[maxEP,idx2]=max(epsilon);
[maxLMTD, idx3]=max(LMTD);
fprintf('Max Efficiency: %.4f at %.4f \n', maxETA, idx1);
fprintf('Max Effectiveness: %.4f at %.4f \n', maxEP, idx2);
fprintf('Max LMTD: %.4f at %.4f \n', maxLMTD, idx3);



%eta plot
figure;
hold on;
plot(time, eta, '-r', "LineWidth", 2);
xlabel('Time (s)');
ylabel('Efficiency (\eta)');
axis padded;
hold off;

%epsilon plot
figure;
hold on;
plot(time, epsilon, '-b', "LineWidth", 2);
xlabel('Time (ms)');
ylabel('Effectiveness (\epsilon)');
hold off;

figure;
hold on;
plot(hotDelta, eta, '-r', "LineWidth", 2);
ylabel('Efficiency (\eta)');
xlabel('Hot Side Delta');


figure;
hold on;
plot(hotDelta, epsilon, '-b', "LineWidth", 2);
ylabel('Effectiveness (\epsilon)');
xlabel('Hot Side Delta');